---
variables:
  - &platforms 'linux/amd64,linux/arm64'
  - &build_plugin 'woodpeckerci/plugin-docker-buildx'

steps:
  publish:
    image: *build_plugin
    settings:
      dockerfile: Dockerfile
      platforms: *platforms
      repo: ricariel/solarflow-control,git.zyria.de/pyrox/solarflow-control
      mtu: 1400
      tag: [latest, master, "latest-${CI_COMMIT_SHA:0:10}"]
      auto_tag: true
      registry: https://index.docker.io/v1/
      purge: false
      pull_image: false
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://git.zyria.de
          username:
            from_secret: git_username
          password:
            from_secret: git_password
    when:
      event: [push, cron, manual, deployment]
